##Data preprocessing tools

In [5]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**a)read data from different formats**

In [6]:
dataset = pd.read_csv('/One_Direction_Proper_Dataset.csv')

In [7]:
print(dataset)

    S.No.                         Song  \
0       1                         "18"
1       2                       "A.M."
2       3                 "Act My Age"
3       4                      "Alive"
4       5              "Another World"
..    ...                          ...
90     91  "Where Do Broken Hearts Go"
91     92      "Why Don't We Go There"
92     93          "Wishing on a Star"
93     94                     "Wolves"
94     95                    "You & I"

                                            Artist(s)  \
0                                       One Direction
1                                       One Direction
2                                       One Direction
3                                       One Direction
4                                       One Direction
..                                                ...
90                                      One Direction
91                                      One Direction
92  The X Factor Finalists 2011 featuring JLSand O...
93                                      One Direction
94                                      One Direction

                                            Writer(s)           Album(s)  \
0                            Ed Sheeran, Oliver Frank               Four
1   Niall Horan, Liam Payne, Harry Styles, Louis T...   Made in the A.M.
2               John Ryan, Julian Bunetta, Ed Drewett               Four
3   Julian Bunetta, John Ryan, Jamie Scott, Louis ...  Midnight Memories
4   Achraf Jannusi, Bilal Hajji, Eric Sanicola, Ge...       Up All Night
..                                                ...                ...
90  Harry Styles, Julian Bunetta, Ruth-Anne Cunnin...               Four
91  Steve Robson, Claude Kelly, Wayne Hector, Loui...  Midnight Memories
92                                  Billie Rae Calvin                 __
93  Niall Horan, Liam Payne, Will Champlin, Andrew...   Made in the A.M.
94  Jamie Scott, Julian Bunetta, Niall Horan, John...  Midnight Memories

    Year                                             Lyrics
0   2014  [Verse 1: Harry]\nI got a heart and I got a so...
1   2015  [Intro: Harry]\nWon't you stay till the A.M.?\...
2   2014  [Intro]\nOne, two, three, four\n\n[Verse 1: Ni...
3   2013  [Verse 1: Liam]\nMy mother told me I should go...
4   2011  [Verse 1: Liam]\nIt's not me, it's not you, th...
..   ...                                                ...
90  2014  [Verse 1: Niall, All]\nCounted all my mistakes...
91  2013  [Verse 1: Harry Styles]\nI know you want, know...
92  2011  [Chorus: Misha B]\nI'm wishin' on a star\nTo f...
93  2015  [Intro: Harry, All]\nI hear them calling for y...
94  2013  [Verse 1: Niall, Liam]\nI figured it out\nI fi...

[95 rows x 7 columns]

**b)Find shape of data**

In [8]:
dataset.shape

(95, 7)

In [9]:
#finding the datatype of each column
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   S.No.      95 non-null     int64
 1   Song       95 non-null     object
 2   Artist(s)  95 non-null     object
 3   Writer(s)  95 non-null     object
 4   Album(s)   95 non-null     object
 5   Year       95 non-null     int64
 6   Lyrics     95 non-null     object
dtypes: int64(2), object(5)
memory usage: 5.3+ KB

**c)Finding missing values**

In [10]:
dataset.isnull().sum()

S.No.        0
Song         0
Artist(s)    0
Writer(s)    0
Album(s)     0
Year         0
Lyrics       0
dtype: int64

In [11]:
#indexing and selecting data ,sort data
select_data=dataset[["Song","Year"]]

In [12]:
select_data

                           Song  Year
0                          "18"  2014
1                        "A.M."  2015
2                  "Act My Age"  2014
3                       "Alive"  2013
4               "Another World"  2011
..                          ...   ...
90  "Where Do Broken Hearts Go"  2014
91      "Why Don't We Go There"  2013
92          "Wishing on a Star"  2011
93                     "Wolves"  2015
94                    "You & I"  2013

[95 rows x 2 columns]

**d)Find datatype of each column**

In [13]:

# Print data types of each column
dataset.dtypes

S.No.         int64
Song         object
Artist(s)    object
Writer(s)    object
Album(s)     object
Year          int64
Lyrics       object
dtype: object

**E)Find out zeros**

In [14]:
# Count the number of zeros in each column
zero_counts = (dataset == 0).sum()
print("Number of zeros in each column:\n", zero_counts)

Number of zeros in each column:
 S.No.        0
Song         0
Artist(s)    0
Writer(s)    0
Album(s)     0
Year         0
Lyrics       0
dtype: int64

**f)indexing and seleting and sorting data**

In [15]:

# Sort the selected data by 'Year' in ascending order
sorted_data = select_data.sort_values(by='Year', ascending=True)

# Display the sorted data
sorted_data

                        Song  Year
27                  "Heroes"  2010
20           "Forever Young"  2010
31  "I Should've Kissed You"  2011
72                "Stand Up"  2011
34                  "I Wish"  2011
..                       ...   ...
93                  "Wolves"  2015
54            "Never Enough"  2015
58                  "Olivia"  2015
82           "Temporary Fix"  2015
47        "Love You Goodbye"  2015

[95 rows x 2 columns]

**h)count unique values of data , format of each column, converting variable data type (e.g.from long to short, vice versa)**

In [16]:
# Count unique values in each column
unique_counts = dataset.nunique()
print("Number of unique values in each column:\n", unique_counts)

Number of unique values in each column:
 S.No.        95
Song         95
Artist(s)     4
Writer(s)    85
Album(s)      7
Year          6
Lyrics       95
dtype: int64

In [18]:
# Check if 'Year' column exists
if 'Year' in dataset.columns:
    # Convert 'Year' column to int64 (long int)
    dataset['Year'] = dataset['Year'].astype('int64')
    print("\nData types after conversion:")
    print(dataset.dtypes)
else:
    print("'Year' column not found in the dataset.")

Data types after conversion:
S.No.         int64
Song         object
Artist(s)    object
Writer(s)    object
Album(s)     object
Year          int64
Lyrics       object
dtype: object